version: '3.8'
services:
    bot:
      build:
        context: ./
        dockerfile: Dockerfile
      restart: always
      env_file:
        - .env
      depends_on:
        - mongodb

    mongodb:
      image: mongo
      ports:
        - 27017:27017
      volumes:
        - ./mongo_volume:/data/db
      env_file:
        - .env
